### ISSUE TITLE
xclim "time difference between dates with different calendars" on euro-cordex daily data

### ISSUE THREAD

**Issue by christinenam** [euro-cordex/py-cordex#19]
* Cordex Python Package version: '0.2.0a1'
* Python version:
* Operating System:

### Description

Trying to use xclim atmos indices, such as "growing degree days" (tas) and "cumulative Dry Days" (pr), on daily euro-cordex ensemble. 

### What I Did
Using:  https://github.com/euro-cordex/py-cordex/blob/master/notebooks/euro-cordex-ensemble.ipynb
Changed: 'month' data to 'day' data.

Tested xclim index on single file, it works. But using it on the data set, even when I have a single model "GCM-RCM.historical" it crashes because 'the calendars' are different. It may be related to "use_cftime": True vs  "only_use_cftime_datetimes": True   when we use ".to_dataset_dict" See issue: https://github.com/Unidata/cftime/issues/128 

But I could not figure it out. 

Growing degree days Index
Sum of average temperatures above 5.6 °C (°C-days); Rivington et al. (2013)

```python
with dask.config.set(**{'array.slicing.split_large_chuncks': False}):
    for exp in dset_split.keys():
        for name, ds in dset_split[exp].items():
            gdd[name] = xclim.atmos.growing_degree_days(tas=ds, thresh='10.0 degC', freq='YS')
gdd
```

traceback error: ...
```
src/cftime/_cftime.pyx in cftime._cftime.datetime.__sub__()
TypeError: cannot compute the time difference between dates with different calendars
```

**Comment by larsbuntemeyer** [comment]
related to https://github.com/Unidata/cftime/issues/128
