### ISSUE TITLE
how to compute significance and robustness of an ensemble signal?

### ISSUE THREAD

**Issue by larsbuntemeyer** [euro-cordex/py-cordex#33]
### Description

We want to have a function that can compute significance and a function that computes robustness of a climate change signal in the CORDEX ensemble.

### What I Did

I have shown [here](https://nbviewer.org/github/euro-cordex/py-cordex/blob/master/notebooks/euro-cordex-ensemble.ipynb) how we can compute regional warming using the EURO-CORDEX ensemble. We can access the data but how can be compute the significance/robustness?

#### signal to noise ratio
Christensen et al. (2019):

*As a measure of robustness or model agreement, the inter-model standard deviation, which we hereafter refer to as ‘noise’ (N), within each model suite is calculated to overlay the plotted change ‘signal’ (S) with the corresponding S/N ratio plotted as contours.
For an ensemble of independent RCMs with a long-term, mean seasonal average temperature and precipitation of similar
magnitude, the **model-mean state**, as here represented by S, has been demonstrated to be a representative measure of the projected future climate (Collins et al. 2013). Along the same lines, the **model spread**, here represented by N, is often used to represent the ensemble robustness in terms of specifying a range for the projected future climate. In
Figs. 2, 3 and 6, areas with S/N < 1 are depicted with hatching, emphasizing areas of model disagreement. Conversely, regions without hatching thereby exhibit a certain level of robustness. This follows the approach by Laux et al. (2017) and Matte et al. (2019) and to some extent IPCC AR5 (IPCC 2013).*

![Screenshot 2021-11-16 at 22 45 34](https://user-images.githubusercontent.com/5659125/142070918-6f4f4afb-7b4a-49ee-a915-cd8b012d7375.png)

##### standard deviation and model mean

```python
N = ensemble.std(dim='dset_id') # model spread
S = ensemble.mean(dim='dset_id') # model mean state
```

#### uncertainty language

from [AR5 uncertainty guidance](https://www.ipcc.ch/site/assets/uploads/2017/08/AR5_Uncertainty_Guidance_Note.pdf):

![grafik](https://user-images.githubusercontent.com/5659125/142224643-b1f593f5-8262-4a4d-b549-c51022dfc2c2.png)

#### `xclim.ensembles`
`xclim` has implemented AR5 uncertainties in it's [`xclim.ensembles`](https://xclim.readthedocs.io/en/latest/api.html#ensemble-robustness-metrics) module. I already learned a lot from that, it's a greate resource.

### references

https://www.mdpi.com/99468
https://www.ipcc.ch/site/assets/uploads/2018/02/WG1AR5_Chapter12_FINAL.pdf (Discussion 12.1)

**Comment by larsbuntemeyer** [comment]
would also be useful to implement #31 to get easy and consisten access to the ensemble.

**Comment by larsbuntemeyer** [comment]
ensemble statistics in xclim: https://xclim.readthedocs.io/en/stable/api.html#ensemble-robustness-metrics

**Comment by christinenam** [comment]
The statistical significance test will depend on the assumptions regarding the distribution of the climate index. For example, if I want to look at the change in extreme precipitation I need the Mann Whitney U-test, not just a simple T-test.

**Comment by larsbuntemeyer** [comment]
> The statistical significance test will depend on the assumptions regarding the distribution of the climate index. For example, if I want to look at the change in extreme precipitation I need the Mann Whitney U-test, not just a simple T-test.
> 
Yes, that should be easy enough to also wrap into xarray.apply_ufunc since it's also available in numpy.stats

> We also (occasionally) show "Robustness" of the ensemble with 2/3 of the simulations indicating a positive / negative / neutral change, and 1/2 of the simulations showing the change is statistically (in)significant. https://www.adapter-projekt.de/klima-produkte/klimakalender_modular.html#nowhere

can you define what a "neutral change" is?

**Comment by larsbuntemeyer** [comment]
@christinenam if you want to play around with statistics on indicators, you can also use the precomputed cmip5 indicator catalog by @ludwiglierhammer, this example show the cmip5 indicator catalog: https://nbviewer.org/github/larsbuntemeyer/notebooks/blob/main/climdex-catalog.ipynb

**Comment by larsbuntemeyer** [comment]
I think i'm understanding some more of this problem now (with the help of [xlim.ensembles](https://xclim.readthedocs.io/en/stable/_modules/xclim/ensembles/_robustness.html#change_significance))... Just dumping some code ideas here.

Implementation would be better off to be upstream in `xclim`, just need to experiment with it here.

```python
import scipy.stats as spstats
import xarray as xr


def significance(fut, ref, member_dim='dset_id', test='ttest', p_change=0.05):
    """Compute significance of change in future period with respect to reference period.

    Returns the fraction of ensemble members that shows significant change and the fraction
    that shows positive change.
    """
    delta = fut.mean("time") - ref.mean("time")
    n_valid_real = fut.notnull().all("time").sum(member_dim)
    
    if test=='ttest':
        pvals = ttest(fut, ref, member_dim)
    elif test=='welch':
        pvals = welch(fut, ref, member_dim)
    elif test=='mannwhitney':
        pvals = mannwhitney(fut, ref, member_dim)
    
    # When p < p_change, the hypothesis of no significant change is rejected.
    changed = pvals < p_change
    
    # compute change
    delta_chng = delta.where(changed)
    # fraction of models that show change
    change_frac = changed.sum(member_dim) / n_valid_real

    # Test that models agree on the sign of the change
    # This returns NaN (cause 0 / 0) where no model show significant change.
    pos_frac = (delta_chng > 0).sum(member_dim) / (change_frac * n_valid_real)
    
    return change_frac, pos_frac


def ttest(fut, ref, member_dim='dset_id'):  
    # Test hypothesis of no significant change
    pvals = xr.apply_ufunc(
        lambda f, r: spstats.ttest_1samp(f, r, axis=-1, nan_policy="omit")[1],
        fut,
        ref.mean("time"),
        input_core_dims=[[member_dim, "time"], [member_dim]],
        output_core_dims=[[member_dim]],
        vectorize=True,
        dask="parallelized",
        output_dtypes=[float],
        dask_gufunc_kwargs={'allow_rechunk':True}
    )
    return pvals


def welch(fut, ref):
    pvals = xr.apply_ufunc(
        lambda f, r: spstats.ttest_ind(
            f, r, axis=-1, equal_var=False, nan_policy="omit"
        )[1],
        fut,
        ref,
        input_core_dims=[["time"], ["time"]],
        exclude_dims={"time"},
        dask="parallelized",
    )
    return pvals


def mannwhitney(fut, ref):
    """wrap spstats.mannwhitneyu into xr.apply_ufunc"""
    pvals = xr.apply_ufunc(
        lambda f, r: spstats.mannwhitneyu(
            f, r, axis=-1
        )[1],
        fut,
        ref,
        input_core_dims=[["time"], ["time"]],
        exclude_dims={"time"},
        dask="parallelized",
    )
    return pvals
```

**Comment by larsbuntemeyer** [comment]
pinging @KatharinaBuelow for her expertise!

**Comment by christinenam** [comment]
We need to change the "def" a bit, because your are returning the 'robustness'. You can also have a robust ensemble that returns significant negative change.

def significance(fut, ref, member_dim='dset_id', test='ttest', p_change=0.05):
    """Compute significance of change in future period with respect to reference period.

    Returns the fraction of ensemble members that shows significant change and the fraction
    that shows significant positive change.

**Comment by larsbuntemeyer** [comment]
> We need to change the "def" a bit, because your are returning the 'robustness'. You can also have a robust ensemble that returns significant negative change.
> 
> def significance(fut, ref, member_dim='dset_id', test='ttest', p_change=0.05): """Compute significance of change in future period with respect to reference period.
> 
> ```
> Returns the fraction of ensemble members that shows significant change and the fraction
> that shows significant positive change.
> ```

yes, you can compute that from the positive change fraction like `(1 - pos_frac) * change_frac`

**Comment by christinenam** [comment]
> can you define what a "neutral change" is? is that simply computing the change as we have done it in the [notebook](https://nbviewer.org/github/euro-cordex/py-cordex/blob/master/notebooks/euro-cordex-ensemble.ipynb) and then look at a certain range of temporal mean? Does it have to be the change in rolling mean?

Using the definitions on pg. 4: https://www.climate-service-center.de/imperia/md/content/csc/projekte/klimasignalkarten/gerics_klimaausblick_hamburg_version1.2_deutsch.pdf 

We need to figure out, for each region of interest (ex. budessland), if 50% of the ensemble members have significant change, but less than 2/3 of the ensemble members.

**Comment by KatharinaBuelow** [comment]
https://github.com/IPCC-WG1/Atlas

**Comment by larsbuntemeyer** [comment]
thanks for all your great expertises here! i think, we can soon implement this and i'll add some documentation!

**Comment by huard** [comment]
Just saw this. We'd be happy to get PRs for improvements to xclim with regards to robustness metrics.

**Comment by larsbuntemeyer** [comment]
@huard thanks for dropping in, really appreciated! @ludwiglierhammer would you be willing to add `mannwhitneyu` to xclim if you are available (I now consider you the expert in significance and robustness metrics :))?
