### ISSUE TITLE
Distinguishing between "region weighting" and "grid weights"

### ISSUE THREAD

**Issue by christinenam** [euro-cordex/py-cordex#43]
* Cordex Python Package version:
* Python version:
* Operating System:

### Description

I would like to ensure that we distinguish between different types of grid weighting.

Global weights, dependent on model grid and lat/lon coordinates. Example: cdo fldmean accounts for how grid boxes over tropics vs north pole differ.

Regional weighing applicable when selecting small region of interest, relative to the model grid. Example: extracting or calculating new index for small bundessland or city from CORDEX simulations.

### Is this the same:

```python
def regional_mean_germany(ds):
    """compute weighted regional means for germany"""
    mask = cx.regions.germany.regionmask().mask_3D(ds)
    weight = np.cos(np.deg2rad(ds.rlat))
    return ds.weighted(mask * weight).mean(dim=("rlat", "rlon"))

```

versus: 

# ROI weighting definitions #

```python
def create_weighted_mask(geodataframe, ref_ds, method="weights_rot_pole"):
    pole = (ref_ds.rotated_latitude_longitude.grid_north_pole_longitude,
            ref_ds.rotated_latitude_longitude.grid_north_pole_latitude)
    central = ref_ds.rotated_latitude_longitude.north_pole_grid_longitude
    return regionmask.mask_geopandas(geodataframe, 
                                     ref_ds.rlon,
                                     ref_ds.rlat,
                                     method=method,
                                     pole_longitude=pole[0],
                                     pole_latitude=pole[1],
                                     central_rotated_longitude=central,
                                     globe='WGS84',
                                     crs=geodataframe.crs)

def weighted(da:xr.DataArray, weights:xr.DataArray):
    if 'time' in da.dims:
        copy = da.isel(time=0)
    else:
        copy = da.copy(deep=True)
    copy.values = weights.values
    return da.weighted(copy.fillna(0))

def weighted_mean(da:xr.DataArray, weights:xr.DataArray, dim=('rlon','rlat')):
    return weighted(da, weights).mean(dim=dim)
```

**Comment by larsbuntemeyer** [comment]
#### spatial weigthing
for the spatial weighting, on should usually use the `areacella` variable. if that's not available, there are different approaches to compute the cell area. `cdo` probably does something similar dependent on your grid mapping. the `np.cos(np.deg2rad(ds.rlat))` formula is sufficient for regular lat lon grids (which the rotated grid actually is).

#### mask weighting
For masking small regions, one can compute the intersection of shapes with the grid using conservative remapping, e.g., this is related to [this](https://nbviewer.org/github/euro-cordex/py-cordex/blob/master/notebooks/weighted-masking.ipynb) notebook and [this (more verbose)](https://nbviewer.org/github/larsbuntemeyer/notebooks/blob/main/masking-germany-eur-11.ipynb). this requires #34 to be resolved finally!

**Comment by larsbuntemeyer** [comment]
this is related to #45
